fall back to float16 when bfloat16 not supported.
In T4 gpu on GCP, got following error:

RuntimeError: Current CUDA Device does not support bfloat16. Please switch dtype to float16.